# Generated by kpex 0.3.7
crashbackups stop
drc off
gds read /home/ic_design_trg/lna_ihp/klayout/inv.gds
load inv
select top cell
flatten inv_flat
load inv_flat
cellname delete inv -noprompt
cellname rename inv_flat inv
select top cell
extract path /home/ic_design_trg/lna_ihp/klayout/output/inv__inv/magic_CC
extract all
ext2spice short none
ext2spice merge none
ext2spice cthresh 0.01
ext2spice subcircuits top on
ext2spice format ngspice
ext2spice -p /home/ic_design_trg/lna_ihp/klayout/output/inv__inv/magic_CC -o /home/ic_design_trg/lna_ihp/klayout/output/inv__inv/magic_CC/inv.pex.spice
quit -noprompt